/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uni.aed.cc232a20224041gpc1;
import java.awt.event.KeyEvent;
import javax.swing.*;
import uni.aed.biblioteca.Libro;
import uni.aed.linkedlistTDA.LinkedListTDA;
import uni.aed.listTDA.ListTDA;
/**
 *
 * @author USUARIO
 */
public class FrmBiblioteca extends javax.swing.JFrame {
     private final DefaultListModel mLDirectorio = new DefaultListModel();
     private final String CADENA_VACIA = "";
     ListTDA<Libro> linkedListTDALibros;
     ListTDA<Libro> linkedListTDAPrestamos;
     ListTDA<Libro> linkedListTDADevoluciones;    
    /**
     * Creates new form FrmBiblioteca
     */
    public FrmBiblioteca() {
        initComponents();
        jLDirectorio.setModel(mLDirectorio);
        jTPGestionBiblioteca.setSelectedIndex(-1);
        linkedListTDALibros = new LinkedListTDA<>();
        linkedListTDAPrestamos= new LinkedListTDA<>();
        linkedListTDADevoluciones= new LinkedListTDA<>();
        jTFnombreLibro.requestFocus();
        jTFnombrePrestatario.requestFocus();
        jTFNombrePrestatario.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jFrame1 = new javax.swing.JFrame();
        popupMenu1 = new java.awt.PopupMenu();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jFrame4 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jBOption1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jBOption2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jBOption3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jBSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTPGestionBiblioteca = new javax.swing.JTabbedPane();
        jPOption1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTFnombreLibro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTFnombreAutor = new javax.swing.JTextField();
        jBAgregarLibro = new javax.swing.JButton();
        jBLimpiar1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jTFCantidad = new javax.swing.JTextField();
        jPOption2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTFnombrePrestatario = new javax.swing.JTextField();
        jTFfechaPrestamo = new javax.swing.JTextField();
        jTFfechaDevolucion = new javax.swing.JTextField();
        jTFlibroPrestado = new javax.swing.JTextField();
        jBRegistrar = new javax.swing.JButton();
        jBLimpiar = new javax.swing.JButton();
        jPOption3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTFNombrePrestatario = new javax.swing.JTextField();
        jTFFechaDevolucion = new javax.swing.JTextField();
        jTFNombreLibroDevuelto = new javax.swing.JTextField();
        jBRegistrarDevolucion = new javax.swing.JButton();
        jBLimpiar2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLDirectorio = new javax.swing.JList<>();
        jLabel19 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        popupMenu1.setLabel("popupMenu1");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        javax.swing.GroupLayout jFrame4Layout = new javax.swing.GroupLayout(jFrame4.getContentPane());
        jFrame4.getContentPane().setLayout(jFrame4Layout);
        jFrame4Layout.setHorizontalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame4Layout.setVerticalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 227));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Selecciona la actividad que deseas realizar");

        jBOption1.setBackground(new java.awt.Color(255, 255, 153));
        jBOption1.setText("1");
        jBOption1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOption1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Agregar Libro");

        jBOption2.setBackground(new java.awt.Color(51, 204, 255));
        jBOption2.setText("2");
        jBOption2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOption2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Registrar préstamo");

        jBOption3.setBackground(new java.awt.Color(255, 102, 153));
        jBOption3.setText("3");
        jBOption3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOption3ActionPerformed(evt);
            }
        });

        jLabel5.setText("Registrar devolución");

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBSalir)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBOption2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBOption1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBOption3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addComponent(jLabel2))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBOption1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBOption2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBOption3)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jBSalir)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel1.setText("¡Bienvenid@ a la Biblioteca!");

        jTPGestionBiblioteca.setBackground(new java.awt.Color(255, 255, 255));

        jPOption1.setBackground(new java.awt.Color(255, 255, 181));
        jPOption1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Agregar Libro");

        jLabel7.setText("1. Ingresa el nombre del libro");

        jTFnombreLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnombreLibroActionPerformed(evt);
            }
        });
        jTFnombreLibro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFnombreLibroKeyPressed(evt);
            }
        });

        jLabel8.setText("2. Ingresa el nombre del autor");

        jTFnombreAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnombreAutorActionPerformed(evt);
            }
        });
        jTFnombreAutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFnombreAutorKeyPressed(evt);
            }
        });

        jBAgregarLibro.setText("Agregar");
        jBAgregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarLibroActionPerformed(evt);
            }
        });

        jBLimpiar1.setText("Limpiar");
        jBLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiar1ActionPerformed(evt);
            }
        });

        jLabel18.setText("3. Ingrese la cantidad de copias ");

        jTFCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFCantidadKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPOption1Layout = new javax.swing.GroupLayout(jPOption1);
        jPOption1.setLayout(jPOption1Layout);
        jPOption1Layout.setHorizontalGroup(
            jPOption1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOption1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPOption1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPOption1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(jTFCantidad))
                    .addComponent(jLabel6)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPOption1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTFnombreLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPOption1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(27, 27, 27)
                        .addGroup(jPOption1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPOption1Layout.createSequentialGroup()
                                .addComponent(jBAgregarLibro)
                                .addGap(27, 27, 27)
                                .addComponent(jBLimpiar1))
                            .addComponent(jTFnombreAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPOption1Layout.setVerticalGroup(
            jPOption1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOption1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPOption1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTFnombreLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPOption1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTFnombreAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPOption1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTFCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPOption1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAgregarLibro)
                    .addComponent(jBLimpiar1))
                .addGap(40, 40, 40))
        );

        jTPGestionBiblioteca.addTab("1", jPOption1);

        jPOption2.setBackground(new java.awt.Color(209, 232, 255));
        jPOption2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Registrar préstamo");

        jLabel10.setText("1. Ingrese el nombre del prestatario");

        jLabel11.setText("2. Ingrese la fecha del préstamo(dd/mm/yy) :");

        jLabel12.setText("3. Ingrese fecha de devolución(dd/mm/yy) : ");

        jLabel13.setText("4. Ingrese el nombre del libro a prestar");

        jTFnombrePrestatario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFnombrePrestatarioKeyPressed(evt);
            }
        });

        jTFfechaPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFfechaPrestamoActionPerformed(evt);
            }
        });

        jTFlibroPrestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFlibroPrestadoActionPerformed(evt);
            }
        });

        jBRegistrar.setText("Registrar");
        jBRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistrarActionPerformed(evt);
            }
        });

        jBLimpiar.setText("Limpiar");
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPOption2Layout = new javax.swing.GroupLayout(jPOption2);
        jPOption2.setLayout(jPOption2Layout);
        jPOption2Layout.setHorizontalGroup(
            jPOption2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOption2Layout.createSequentialGroup()
                .addGroup(jPOption2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPOption2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPOption2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPOption2Layout.createSequentialGroup()
                                .addGroup(jPOption2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(28, 28, 28)
                                .addGroup(jPOption2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFfechaDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFlibroPrestado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPOption2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPOption2Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(25, 25, 25)
                                    .addComponent(jTFfechaPrestamo))
                                .addGroup(jPOption2Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(78, 78, 78)
                                    .addComponent(jTFnombrePrestatario, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPOption2Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jBRegistrar)
                        .addGap(18, 18, 18)
                        .addComponent(jBLimpiar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPOption2Layout.setVerticalGroup(
            jPOption2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOption2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPOption2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTFnombrePrestatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPOption2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTFfechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPOption2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTFfechaDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPOption2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTFlibroPrestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPOption2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBRegistrar)
                    .addComponent(jBLimpiar))
                .addGap(17, 17, 17))
        );

        jTPGestionBiblioteca.addTab("2", jPOption2);

        jPOption3.setBackground(new java.awt.Color(255, 190, 190));
        jPOption3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Registrar devolución");

        jLabel15.setText("1. Ingrese el nombre del prestatario: ");

        jLabel16.setText("2. Ingrese la fecha de devolución(dd/mm/yy): ");

        jLabel17.setText("3. Ingrese el nombre del libro devuelto: ");

        jTFNombrePrestatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNombrePrestatarioActionPerformed(evt);
            }
        });

        jTFFechaDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFFechaDevolucionActionPerformed(evt);
            }
        });

        jTFNombreLibroDevuelto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNombreLibroDevueltoActionPerformed(evt);
            }
        });

        jBRegistrarDevolucion.setText("Registrar");
        jBRegistrarDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistrarDevolucionActionPerformed(evt);
            }
        });

        jBLimpiar2.setText("Limpiar");
        jBLimpiar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPOption3Layout = new javax.swing.GroupLayout(jPOption3);
        jPOption3.setLayout(jPOption3Layout);
        jPOption3Layout.setHorizontalGroup(
            jPOption3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOption3Layout.createSequentialGroup()
                .addGroup(jPOption3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPOption3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPOption3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(jPOption3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPOption3Layout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTFNombreLibroDevuelto, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPOption3Layout.createSequentialGroup()
                                    .addGroup(jPOption3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel16))
                                    .addGap(35, 35, 35)
                                    .addGroup(jPOption3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTFFechaDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTFNombrePrestatario, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPOption3Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jBRegistrarDevolucion)
                        .addGap(18, 18, 18)
                        .addComponent(jBLimpiar2)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPOption3Layout.setVerticalGroup(
            jPOption3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOption3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPOption3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTFNombrePrestatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPOption3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTFFechaDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPOption3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTFNombreLibroDevuelto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPOption3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBRegistrarDevolucion)
                    .addComponent(jBLimpiar2))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTPGestionBiblioteca.addTab("3", jPOption3);

        jScrollPane1.setViewportView(jLDirectorio);

        jLabel19.setText("Gestion biblioteca");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel19))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jTPGestionBiblioteca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jTPGestionBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBOption1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOption1ActionPerformed
        // TODO add your handling code here:
        jTPGestionBiblioteca.setSelectedIndex(0);
        
    }//GEN-LAST:event_jBOption1ActionPerformed

    private void jBOption2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOption2ActionPerformed
        // TODO add your handling code here:
        jTPGestionBiblioteca.setSelectedIndex(1);
        
    }//GEN-LAST:event_jBOption2ActionPerformed

    private void jBOption3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOption3ActionPerformed
        // TODO add your handling code here:
        jTPGestionBiblioteca.setSelectedIndex(2);
        
    }//GEN-LAST:event_jBOption3ActionPerformed

    private void jTFnombreLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnombreLibroActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTFnombreLibroActionPerformed

    private void jTFnombreAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnombreAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnombreAutorActionPerformed

    private void jBAgregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarLibroActionPerformed
        // TODO add your handling code here:
        agregarLibro();
    }//GEN-LAST:event_jBAgregarLibroActionPerformed

    private void agregarLibro(){
        
        String nombreLibro = jTFnombreLibro.getText();
        String nombreAutor = jTFnombreAutor.getText();
        int cantidadCopias = Integer.parseInt(jTFCantidad.getText());
        
        Libro libroNuevo = new Libro(nombreLibro, nombreAutor, cantidadCopias);
        mLDirectorio.addElement(libroNuevo);
        linkedListTDALibros.add(libroNuevo);
        clearEntryOption1();
    }
    private void clearEntryOption1(){
        jTFnombreLibro.setText(CADENA_VACIA);
        jTFnombreAutor.setText(CADENA_VACIA);
        jTFCantidad.setText(CADENA_VACIA);
        
        jTFnombreLibro.requestFocus();
    }
    private void clearEntryOption2(){
        jTFnombrePrestatario.setText(CADENA_VACIA);
        jTFfechaPrestamo.setText(CADENA_VACIA);
        jTFfechaDevolucion.setText(CADENA_VACIA);
        jTFlibroPrestado.setText(CADENA_VACIA);
    }
    private void clearEntryOption3(){
        jTFNombrePrestatario.setText(CADENA_VACIA);
        jTFFechaDevolucion.setText(CADENA_VACIA);
        jTFNombreLibroDevuelto.setText(CADENA_VACIA);
        
    }
    
    private void jTFfechaPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFfechaPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFfechaPrestamoActionPerformed

    private void jTFlibroPrestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFlibroPrestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFlibroPrestadoActionPerformed

    private void jBRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBRegistrarActionPerformed

    private void jTFNombreLibroDevueltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNombreLibroDevueltoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombreLibroDevueltoActionPerformed

    private void jBRegistrarDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistrarDevolucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBRegistrarDevolucionActionPerformed

    private void jTFnombreLibroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFnombreLibroKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            jTFnombreAutor.requestFocus();
        }
    }//GEN-LAST:event_jTFnombreLibroKeyPressed

    private void jTFnombreAutorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFnombreAutorKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            
            jTFCantidad.requestFocus();
        }
    }//GEN-LAST:event_jTFnombreAutorKeyPressed

    private void jTFnombrePrestatarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFnombrePrestatarioKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jTFfechaPrestamo.requestFocus();
        }
    }//GEN-LAST:event_jTFnombrePrestatarioKeyPressed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jTFNombrePrestatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNombrePrestatarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombrePrestatarioActionPerformed

    private void jBLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiar1ActionPerformed
        // TODO add your handling code here:
        clearEntryOption1();
    }//GEN-LAST:event_jBLimpiar1ActionPerformed

    private void jTFFechaDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFFechaDevolucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFFechaDevolucionActionPerformed

    private void jBLimpiar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiar2ActionPerformed
        // TODO add your handling code here:
        clearEntryOption3();
        
    }//GEN-LAST:event_jBLimpiar2ActionPerformed

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
        // TODO add your handling code here:
        clearEntryOption2();
    }//GEN-LAST:event_jBLimpiarActionPerformed

    private void jTFCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCantidadKeyPressed
        // TODO add your handling code here:
        jBAgregarLibro.requestFocus();
    }//GEN-LAST:event_jTFCantidadKeyPressed

    
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBiblioteca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregarLibro;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JButton jBLimpiar1;
    private javax.swing.JButton jBLimpiar2;
    private javax.swing.JButton jBOption1;
    private javax.swing.JButton jBOption2;
    private javax.swing.JButton jBOption3;
    private javax.swing.JButton jBRegistrar;
    private javax.swing.JButton jBRegistrarDevolucion;
    private javax.swing.JButton jBSalir;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JFrame jFrame4;
    private javax.swing.JList<String> jLDirectorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPOption1;
    private javax.swing.JPanel jPOption2;
    private javax.swing.JPanel jPOption3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCantidad;
    private javax.swing.JTextField jTFFechaDevolucion;
    private javax.swing.JTextField jTFNombreLibroDevuelto;
    private javax.swing.JTextField jTFNombrePrestatario;
    private javax.swing.JTextField jTFfechaDevolucion;
    private javax.swing.JTextField jTFfechaPrestamo;
    private javax.swing.JTextField jTFlibroPrestado;
    private javax.swing.JTextField jTFnombreAutor;
    private javax.swing.JTextField jTFnombreLibro;
    private javax.swing.JTextField jTFnombrePrestatario;
    private javax.swing.JTabbedPane jTPGestionBiblioteca;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
